import { StyleSheet } from 'react-native';
import { THEME } from './globalStyles';

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.light.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  formContainer: {
    flex: 1,
    width: '100%',
    maxWidth: 600,
    padding: 30,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 10,
    color: THEME.colors.light.foreground,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: THEME.colors.light.foregroundMuted,
    marginBottom: 40,
    textAlign: 'center',
  },
  formGroup: {
    marginBottom: 25,
    zIndex: 1,
  },
  label: {
    fontSize: 18,
    fontWeight: '600',
    color: THEME.colors.light.foreground,
    marginBottom: 10,
  },
  pickerContainer: {
    backgroundColor: THEME.colors.light.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.colors.light.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  picker: {
    height: 50,
  },
  submitButton: {
    backgroundColor: THEME.colors.light.primary,
    padding: 15,
    borderRadius: 10,
    marginTop: 20,
    marginBottom: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 1,
    zIndex: -1,
  },
  submitButtonText: {
    color: THEME.colors.light.onPrimary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  dropdownWrapper: {
    position: 'relative',
    zIndex: 9999,
  },
  dropdownButton: {
    backgroundColor: THEME.colors.light.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.colors.light.border,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownButtonText: {
    fontSize: 16,
    color: THEME.colors.light.foreground,
  },
  dropdownArrow: {
    fontSize: 12,
    color: THEME.colors.light.foregroundMuted,
  },
  dropdownList: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: THEME.colors.light.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.colors.light.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 9999,
    zIndex: 9999,
  },
  dropdownItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.light.borderLight,
  },
  dropdownItemText: {
    fontSize: 16,
    color: THEME.colors.light.foreground,
  },

  assignedLineText: {
    backgroundColor: THEME.colors.light.card,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.colors.light.border,
    textAlign: 'center',
    color: THEME.colors.light.foreground,
    fontWeight: '600',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: THEME.colors.light.overlayModal,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    backgroundColor: THEME.colors.light.card,
    borderRadius: 12,
    padding: 16,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  modalItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.light.borderLight,
  },
  modalItemText: {
    fontSize: 15,
    color: THEME.colors.light.foreground,
  },
  modalCancel: {
    padding: 10,
  },
  modalDanger: {
    backgroundColor: THEME.colors.light.danger,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  }
});

