import { StyleSheet } from 'react-native';

export const protocolScreenStyles = StyleSheet.create({
  buttonSize: {
    width: 220,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    marginBottom: 12,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonIconSmall: {
    fontSize: 18,
    color: '#ffffff',
    marginRight: 12,
  },
  buttonLabelOnButton: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  startButton: {
    backgroundColor: '#22c55e', // grün
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  pauseButton: {
    backgroundColor: '#06b6d4', // türkis-blau
    shadowColor: '#06b6d4',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  endeButton: {
    backgroundColor: '#f59e42', // orange
    shadowColor: '#f59e42',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    gap: 64,
  },
  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 40,
    paddingVertical: 25,
  },
  bigTitle: {
    fontSize: 44,
    fontWeight: '700',
    color: '#1e293b',
    textAlign: 'center',
    marginTop: 25,
    marginBottom: 35,
  },
  titleInfoRow: {
    fontSize: 22,
    fontWeight: '600',
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 18,
    opacity: 0.92,
    letterSpacing: 0.4,
  },
  infoRowBig: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    marginBottom: 40,
    gap: 30,
    paddingHorizontal: 20,
  },
  infoBox: {
    flex: 1,
    maxWidth: 350,
    borderRadius: 16,
    padding: 22,
    backgroundColor: '#ffffff',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  infoLabelBig: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 10,
  },
  infoValueBig: {
    marginBottom: 10,
    color: '#1e293b',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 18,
    color: '#64748b',
    marginBottom: 30,
    textAlign: 'center',
  },
  infoCard: {
    backgroundColor: '#ffffff',
    padding: 25,
    borderRadius: 16,
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 20,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  infoLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#475569',
  },
  infoValue: {
    fontSize: 18,
    color: '#3b82f6',
    fontWeight: 'bold',
  },
  buttonContainer: {
    marginTop: 10,
    alignItems: 'center',
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 8,
    paddingRight: 24,
  },
  leftButtonColumn: {
    alignSelf: 'flex-start',
    marginLeft: 24,
    marginTop: 0,
    width: 240,
  },
  buttonStackItem: {
    marginBottom: 12,
  },
  buttonIcon: {
    fontSize: 20,
    color: '#ffffff',
    textAlign: 'center',
  },
  timerColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 20,
  },
  timerCenteredContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 6,
  },
  buttonsRowCentered: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 28,
    marginTop: 18,
    flexWrap: 'wrap',
  },
  selectedIssueText: {
    color: '#ef4444',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
    fontWeight: '600',
  },
  stoerTimerText: {
    color: '#dc2626',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
  },
  tableContainer: {
    width: '100%',
    marginTop: 18,
    paddingHorizontal: 24,
    height: 260, /* fixed height so table does not grow; fits ~5 rows + header */
  },
  tableTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 8,
  },
  smallDangerButton: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 14,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2f7',
  },
  tableCell: {
    flex: 1,
    color: '#475569',
    fontSize: 14,
    textAlign: 'center',
  },
  tableEmpty: {
    color: '#94a3b8',
    fontSize: 14,
    paddingVertical: 10,
  },
  tableScroll: {
    // fixed scroll height to show ~5 rows; table won't grow larger
    height: 220,
    marginTop: 6,
  },
  timerContainer: {
    alignItems: 'center',
  },
  timerText: {
    fontSize: 52,
    fontWeight: '700',
    color: '#0f172a',
    opacity: 0.95,
    letterSpacing: 0.5,
  },
  timerChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    minWidth: 80,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  timerChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    minWidth: 76,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerChipText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  /* Modal styles */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
  },
  modalMessage: {
    fontSize: 15,
    color: '#475569',
    marginBottom: 18,
  },
  modalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  modalCancel: {
    backgroundColor: '#f1f5f9',
  },
  modalConfirm: {
    backgroundColor: '#ef4444',
  },
  modalCancelText: {
    color: '#475569',
    fontWeight: '600',
  },
  modalConfirmText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  timerChipGreen: {
    backgroundColor: '#16a34a',
  },
  timerChipRed: {
    backgroundColor: '#dc2626',
  },
  timerChipPause: {
    backgroundColor: '#0284c7',
  },
  timerChipNeutral: {
    backgroundColor: '#e6eef7',
  },
  actionButton: {
    backgroundColor: '#ef4444',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
    marginBottom: 12,
  },
  // Active states for visual feedback
  startButtonActive: {
    backgroundColor: '#16a34a',
    shadowColor: '#16a34a',
    shadowOpacity: 0.6,
    elevation: 12,
  },
  actionButtonActive: {
    backgroundColor: '#dc2626',
    shadowColor: '#dc2626',
    shadowOpacity: 0.6,
    elevation: 12,
  },
  pauseButtonActive: {
    backgroundColor: '#0284c7',
    shadowColor: '#0284c7',
    shadowOpacity: 0.6,
    elevation: 12,
  },
  // Timer color states
  timerGreen: {
    color: '#16a34a',
  },
  timerRed: {
    color: '#dc2626',
  },
  timerPause: {
    color: '#0284c7',
  },
  actionButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  backButton: {
    position: 'absolute',
    right: 32,
    bottom: 8,
    backgroundColor: '#ffffff',
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 36,
    alignItems: 'center',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 10,
  },
  backButtonText: {
    color: '#64748b',
    fontSize: 16,
    fontWeight: '600',
  },
});
